import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ResponsiveNav from "@/components/Home/Nav.tsx/ResponsiveNav";
import "./globals.css";

const font = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${font.className} antialiased bg-[#0C0D1F]`}>
          <ResponsiveNav/>
          {children}
      </body>
    </html>
  );
}
